version: '3'
services:
  django:
    build: ./django
    volumes:
      - ./django:/usr/src/django
    command: python3 manage.py runserver 0:8000
    tty: true
    ports:
      - "8000:8000"
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d/"
      - "./django/project/static:/opt/apps/static/"
  node:
    build: ./node
    ports:
      - "5555:80"
    volumes:
      - ./sass:/sass
      - ./django/project/static/css:/css
    stdin_open: true
